[build]
    publish = "dist/"
    command = "npx vite build"

[[redirects]]
    from = "/src/assets/*"
    to = "/"
    status = 200

#[context.production]
#  publish = "dist/"
#  command = "npm run dev"

#[context.deploy-preview]
#  publish = "dist/"

#[context.branch-deploy.environment]
#  NODE_ENV = "development"