[build]
    publish = "dist/"
    command = "npx vite build"

[[redirects]]
    from = "/src/assets/img/wm.svg"
    to = "/img/wm.svg"

[[redirects]]
    from = "/src/assets/img/*"
    to = "/img/*"

#[context.production]
#  publish = "dist/"
#  command = "npm run dev"

#[context.deploy-preview]
#  publish = "dist/"

#[context.branch-deploy.environment]
#  NODE_ENV = "development"