export {NavigatePage} from './nav';
export {LoginPage} from './login';
export {RegPage} from './registrate';
export {ProfilePage} from './profile';
export {ChatPage} from './chat';
export {ErrorPage} from './error';
export {ModalChangePasswd} from './modals/modal_change_passwd';
export {ModalChangeAvatar} from './modals/modal_change_avatar';
export {RememberPassword} from './remember_password';